const jokes = [
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a fake noodle? An impasta.",
    "Why don't ants get sick? Because they have tiny ant-bodies!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don't oysters share their pearls? Because they're shellfish.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why couldn't the bicycle stand up by itself? Because it was two-tired.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "What do you get when you cross a vampire and a snowman? Frostbite.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you call a bear with no ears? B.",
    "Why do bees hum? Because they don't know the words.",
    "What do you get when you cross a snowman and a baker? Frosty the Doughman.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "Why did the grape stop in the middle of the road? Because it ran out of juice.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why was the broom late? It swept in.",
    "What do you get when you cross a frog and a rabbit? A jump hare.",
    "What do you call a dinosaur that's sleeping? A dino-snore.",
    "Why did the teddy bear say no to dessert? Because it was already stuffed.",
    "What do you get when you cross a snowman and a baker? Frosty the Doughman.",
    "Why did the cookie go to the doctor? Because it was feeling crummy.",
    "What do you call a cow that can play an instrument? A moosician.",
    "What do you call a bird that's afraid to fly? A chicken.",
    "Why don't ghosts use elevators? Because they lift their spirits.",
    "What do you get when you cross a snowman and a snowwoman? Snowballs.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "What do you get when you cross a horse and a pencil? A stable pencil.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the fish blush? Because it saw the ocean's bottom.",
    "What do you get when you cross a snowman and a baker? Frosty the Doughman.",
    "What do you get when you cross a tiger and a snowman? A brrrrr-rrrrr.",
    "Why did the clock go to the principal's office? For tocking too much.",
    "What did the big flower say to the little flower? 'Hey, bud!'",
    "Why did the computer go to the doctor? Because it had a virus.",
    "What do you get when you cross a snowman and a bulldozer? Frost",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call a fish wearing a crown? King Neptune!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "How do you organize a space party? You planet!",
    "Why did the math book look sad? Because it had too many problems!",
    "What do you call a dinosaur that is sleeping? A dino-snore!",
    "Why don't vampires go to barbecues? They don't like steak!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "What do you call a dog magician? A labracadabrador!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What do you call a bear with no ears? B!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What did the zero say to the eight? Nice belt!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "How do you make a lemon drop? Just let it fall!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the teddy bear say 'no' to dessert? Because it was stuffed!",
    "What's a tornado's favorite game to play? Twister!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "How do you catch a squirrel with a remote control? Press 'pause'!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why don't ducks tell jokes when they fly? Because they would quack up!",
    "What do you call a fish wearing a crown? King of the sea!",
    "How do you organize a space party? You planet!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What did the pencil say to the paper? 'You're looking sharp!'",
    "Why did the bicycle fall over? Because it was two-tired!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a dinosaur that is sleeping? A dino-snore!",
    "Why don't vampires go to barbecues? They don't like steak!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a bear with no ears? B!",
    "What did one wall say to the other wall? 'I'll meet you at the corner!'",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why don't skeletons fight each other? They don't have the guts!"
]

const jokesy = () => {
    const get_random = Math.floor(Math.random() * jokes.length)
    const j = document.getElementById("jk")
    j.innerHTML = jokes[get_random]
}

